version: '3'
services:
  web:
    build: 
      context: ./website
    ports:
      - "3000:3000"
    depends_on:
      - server
  
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: ./server
          target: /usr/src/app
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
