name: ARMv7 Release
on:
  push:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
